# Generated by Django 5.0.1 on 2024-01-21 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions_users',
            field=models.ManyToManyField(related_name='subscribers_users', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
