# Generated by Django 5.0.1 on 2024-02-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
